# Generated by Django 5.2.4 on 2025-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shop', '0002_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
