# Generated by Django 5.2.4 on 2025-07-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shop', '0003_sweet_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sweet_shop.sweet'),
        ),
    ]
